// Load the WASM module generated by wasm-bindgen
import init, { test_cipherbox, greet } from "../pkg/wasm_demo.js";

async function main() {
  // Initialize the WASM module with explicit path
  console.log("🦀 Redoubt WASM Demo (before init)\n");
  // initSync(new URL("./pkg/wasm_demo_bg.wasm", import.meta.url));
  await init();
  console.log("🦀 Redoubt WASM Demo (after init)\n");

  // Test basic greeting
  console.log("Testing greet():");
  console.log(greet("Bun"));
  console.log();

  // Test CipherBox functionality
  console.log("Testing CipherBox:");
  const result = test_cipherbox();
  console.log(result);
  console.log();

  console.log("✅ All tests passed!");

  // Small delay to let Bun cleanup WASM resources
  await new Promise((resolve) => setTimeout(resolve, 100));
  process.exit(0);
}

main().catch((err) => {
  console.error("❌ Error:", err);
  process.exit(1);
});
