#!/usr/bin/env python3
# Copyright (c) 2025-2026 Federico Hoerth <memparanoid@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only
# See LICENSE in the repository root for full license text.

"""Writes hkdf_sha256_digests.txt: one digest per info length, from libsodium.

The answers have to come from libsodium and from nothing else. Regenerating
this file against the implementation it is used to check would freeze whatever
that implementation does today and the test would go on passing for ever
without measuring anything.

Every input is derived rather than written down, so nothing is transcribed
between this file and the Rust that reads it. A seed is the digest of an ASCII
string, and the material of one length is unrelated to the material of any
other because the length goes into the derivation.

The inputs are made with SHA-256 and the algorithm under test is built on
SHA-256. Nothing is riding on that: HKDF does not look at where its bytes came
from, and it is what the published corpora do for their generated cases.

Run: python3 vectors/generate_hkdf_sha256_digests.py
"""

import ctypes
import ctypes.util
import sys
from hashlib import sha256
from pathlib import Path

# The enumeration. Both sides walk it in this order, and a length added here is
# a file that has to be generated again.
INFO_LENGTHS = range(0, 131)
SALT_LENGTHS = (0, 1, 31, 32, 33, 63, 64, 65, 96, 127, 128, 129)
IKM_LENGTHS = (0, 1, 31, 32, 33, 63, 64, 65, 96, 127, 128, 129, 255)
OKM_LENGTHS = (1, 2, 31, 32, 33, 63, 64, 65, 127, 128, 255, 1024)

PRK_SIZE = 32


def seed(field: str) -> bytes:
    """A field's seed, derived so that there is no hexadecimal to transcribe."""
    return sha256(b"redoubt-hkdf-sha256 corpus " + field.encode()).digest()


def material(field: str, length: int) -> bytes:
    """The bytes this field takes at this length.

    The length is in the derivation, so the material of one length is not a
    prefix of the material of a longer one.
    """
    said, counter = b"", 0

    while len(said) < length:
        said += sha256(
            seed(field) + length.to_bytes(4, "big") + counter.to_bytes(4, "big")
        ).digest()
        counter += 1

    return said[:length]


def libsodium() -> ctypes.CDLL:
    """libsodium, wherever this machine keeps it.

    PyNaCl ships one inside its own package, which is what makes this work on a
    system that does not expose the library itself.
    """
    candidates = []

    try:
        import nacl._sodium as bundled

        candidates.append(bundled.__file__)
    except ImportError:
        pass

    found = ctypes.util.find_library("sodium")
    if found:
        candidates.append(found)

    for candidate in candidates:
        try:
            loaded = ctypes.CDLL(candidate)
            loaded.crypto_kdf_hkdf_sha256_extract
        except (OSError, AttributeError):
            continue

        loaded.crypto_kdf_hkdf_sha256_extract.argtypes = [
            ctypes.c_char_p,
            ctypes.c_char_p,
            ctypes.c_size_t,
            ctypes.c_char_p,
            ctypes.c_size_t,
        ]
        loaded.crypto_kdf_hkdf_sha256_expand.argtypes = [
            ctypes.c_char_p,
            ctypes.c_size_t,
            ctypes.c_char_p,
            ctypes.c_size_t,
            ctypes.c_char_p,
        ]

        return loaded

    sys.exit(
        "no libsodium with crypto_kdf_hkdf_sha256 was found. It arrived in "
        "1.0.19; on NixOS, python3Packages.pynacl brings one."
    )


def main() -> None:
    sodium = libsodium()
    lines = []

    for info_len in INFO_LENGTHS:
        info = material("info", info_len)
        row = sha256()

        for salt_len in SALT_LENGTHS:
            salt = material("salt", salt_len)

            for ikm_len in IKM_LENGTHS:
                ikm = material("ikm", ikm_len)

                prk = ctypes.create_string_buffer(PRK_SIZE)
                if sodium.crypto_kdf_hkdf_sha256_extract(
                    prk, salt, salt_len, ikm, ikm_len
                ):
                    sys.exit(f"extract refused salt {salt_len}, ikm {ikm_len}")

                for okm_len in OKM_LENGTHS:
                    okm = ctypes.create_string_buffer(okm_len)
                    if sodium.crypto_kdf_hkdf_sha256_expand(
                        okm, okm_len, info, info_len, prk
                    ):
                        sys.exit(f"expand refused okm {okm_len}")

                    row.update(okm.raw[:okm_len])

        lines.append(f"Info = {info_len}\nMD = {row.hexdigest()}\n")

    ran = len(INFO_LENGTHS) * len(SALT_LENGTHS) * len(IKM_LENGTHS) * len(OKM_LENGTHS)
    header = (
        "# Auto-generated by generate_hkdf_sha256_digests.py\n"
        "# DO NOT EDIT, and never regenerate against redoubt's own implementation\n"
        "# Source: libsodium crypto_kdf_hkdf_sha256\n"
        "#\n"
        f"# One digest per info length, over {ran} derivations.\n"
        "# MD is SHA-256 of every okm of that row, concatenated in the order\n"
        "# salt, then ikm, then okm, each list as the script declares it.\n"
        "\n"
    )

    out = Path(__file__).parent / "hkdf_sha256_digests.txt"
    out.write_text(header + "\n".join(lines))

    print(f"{ran} derivations, {len(lines)} digests -> {out}")


if __name__ == "__main__":
    main()
