#!/usr/bin/env python3
# Copyright (c) 2025-2026 Federico Hoerth <memparanoid@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only
# See LICENSE in the repository root for full license text.

"""
Project insights: generates INSIGHTS.md with code metrics and coverage.
No external dependencies - stdlib only.

Reads coverage from coverage/report.html (generated by coverage.sh).
"""

import json
import subprocess
import re
from pathlib import Path
from datetime import datetime

def run_cmd(cmd, cwd=None):
    """Run command and return output."""
    result = subprocess.run(
        cmd,
        shell=True,
        capture_output=True,
        text=True,
        cwd=cwd
    )
    return result.stdout

def count_tests():
    """How many tests the workspace has, and how many each package has.

    Asked of nextest rather than run: `list` builds the binaries and enumerates
    them, so the count includes the integration tests that `--lib` leaves out
    and the ignored ones that a run would report as skipped.

    The per-package half comes from the same listing, so the breakdown and the
    total are the same measurement told two ways and cannot disagree.
    """
    output = run_cmd("cargo nextest list --workspace --message-format json 2>/dev/null")

    try:
        listing = json.loads(output)
    except json.JSONDecodeError:
        return 0, {}

    by_package = {}

    for suite in listing.get('rust-suites', {}).values():
        package = suite.get('package-name')
        if package:
            by_package[package] = by_package.get(package, 0) + len(suite.get('testcases', {}))

    return listing.get('test-count', 0), by_package

def parse_coverage_html():
    """Parse coverage/report.html generated by coverage.sh."""
    coverage_path = Path('coverage/report.html')
    if not coverage_path.exists():
        return None

    content = coverage_path.read_text()

    # Parse the total-card divs: value and detail
    metrics = {}
    for metric in ['Functions', 'Lines', 'Regions', 'Branches']:
        pattern = (
            rf'<div class="label">{metric}</div>\s*'
            rf'<div class="value [^"]*">([\d.]+)%</div>\s*'
            rf'<div class="detail">(\d+)/(\d+)</div>'
        )
        match = re.search(pattern, content)
        if match:
            metrics[metric.lower()] = {
                'percent': float(match.group(1)),
                'covered': int(match.group(2)),
                'total': int(match.group(3))
            }

    if len(metrics) < 4:
        return None

    return {
        'function': metrics['functions'],
        'line': metrics['lines'],
        'region': metrics['regions'],
        'branch': metrics['branches']
    }

def coverage_color(percentage, exponent=24):
    t = pow(percentage / 100.0, exponent)
    hue = 60 + 60 * t
    return hsl_to_hex(hue, 100, 45)

def hsl_to_hex(h, s, l):
    h, s, l = h / 360.0, s / 100.0, l / 100.0

    def hue_to_rgb(p, q, t):
        if t < 0: t += 1
        if t > 1: t -= 1
        if t < 1/6: return p + (q - p) * 6 * t
        if t < 1/2: return q
        if t < 2/3: return p + (q - p) * (2/3 - t) * 6
        return p

    if s == 0:
        r = g = b = l
    else:
        q = l * (1 + s) if l < 0.5 else l + s - l * s
        p = 2 * l - q
        r = hue_to_rgb(p, q, h + 1/3)
        g = hue_to_rgb(p, q, h)
        b = hue_to_rgb(p, q, h - 1/3)

    return f"{int(r * 255):02x}{int(g * 255):02x}{int(b * 255):02x}"

def update_readme_badges(coverage, audit):
    readme_path = Path('README.md')
    if not readme_path.exists():
        return

    content = readme_path.read_text()

    if coverage:
        pct = coverage['line']['percent']
        color = coverage_color(pct, exponent=24)

        old_badge_pattern = r'<img src="https://img\.shields\.io/badge/coverage-[^"]*" alt="coverage">'
        new_badge = f'<img src="https://img.shields.io/badge/coverage-{pct:.2f}%25-{color}" alt="coverage">'
        content = re.sub(old_badge_pattern, new_badge, content)

    if audit:
        vuln_count = 0 if audit['clean'] else '?'
        vuln_color = 'brightgreen' if audit['clean'] else 'red'

        old_vuln_pattern = r'<img src="https://img\.shields\.io/badge/vulnerabilities-[^"]*" alt="security">'
        new_vuln = f'<img src="https://img.shields.io/badge/vulnerabilities-{vuln_count}-{vuln_color}" alt="security">'
        content = re.sub(old_vuln_pattern, new_vuln, content)

    old_license_pattern = r'<a href="[^"]*"><img src="https://img\.shields\.io/badge/license-[^"]*" alt="license"></a>'
    new_license = '<a href="#license"><img src="https://img.shields.io/badge/license-GPL--3.0--only-blue" alt="license"></a>'
    content = re.sub(old_license_pattern, new_license, content)

    readme_path.write_text(content)

def parse_tokei_rust(output):
    for line in output.split('\n'):
        if line.strip().startswith('Rust'):
            parts = line.split()
            if len(parts) >= 6:
                try:
                    return {
                        'files': int(parts[1].replace(',', '')),
                        'lines': int(parts[2].replace(',', '')),
                        'code': int(parts[3].replace(',', '')),
                        'comments': int(parts[4].replace(',', '')),
                        'blanks': int(parts[5].replace(',', ''))
                    }
                except (ValueError, IndexError):
                    continue
    return None

def find_crates():
    """The workspace members under `crates/`, as (path, package name) pairs.

    Asked of cargo rather than of the directory tree, because `redoubt-aead`
    keeps its backends three levels down and a walk of fixed depth leaves them
    out.

    A member inside another's `src` is one of the fixtures a derive test
    compiles. Cargo adds it to the workspace for being a path dependency, and
    it is not a crate this workspace ships.
    """
    root = Path.cwd()
    output = run_cmd("cargo metadata --no-deps --format-version 1 2>/dev/null")

    try:
        packages = json.loads(output)['packages']
    except (json.JSONDecodeError, KeyError):
        return []

    crates = []

    for package in packages:
        path = Path(package['manifest_path']).parent.relative_to(root)
        if path.parts[:1] == ('crates',) and 'src' not in path.parts:
            crates.append((path, package['name']))

    return sorted(crates)

def count_assertions(path):
    counts = {
        'assert!': 0,
        'assert_eq!': 0,
        'debug_assert!': 0,
        'debug_assert_eq!': 0
    }

    for rust_file in Path(path).rglob('*.rs'):
        try:
            content = rust_file.read_text()
            for macro in counts.keys():
                counts[macro] += content.count(macro)
        except:
            pass

    return counts

def strip_ansi(text):
    return re.sub(r'\x1b\[[0-9;]*m', '', text)

def run_cargo_audit():
    result = subprocess.run(
        "cargo audit 2>&1",
        shell=True,
        capture_output=True,
        text=True
    )
    output = strip_ansi(result.stdout + result.stderr)

    has_vulnerabilities = 'vulnerability' in output.lower() and 'found' in output.lower()

    advisories_match = re.search(r'Loaded (\d+) security advisories', output)
    advisories = int(advisories_match.group(1)) if advisories_match else 0

    crates_match = re.search(r'Scanning.*\((\d+) crate dependencies\)', output)
    crates_scanned = int(crates_match.group(1)) if crates_match else 0

    return {
        'clean': not has_vulnerabilities,
        'advisories': advisories,
        'crates_scanned': crates_scanned
    }


def main():
    lines = []

    lines.append("""<picture>
    <p align="center">
    <source media="(prefers-color-scheme: dark)" width="320" srcset="/logo_light.png">
    <source media="(prefers-color-scheme: light)" width="320" srcset="/logo_light.png">
    <img alt="Redoubt" width="320" src="/logo_light.png">
    </p>
</picture>

<h1 align="center">Project Insights</h1>
""")

    lines.append(f"<p align=\"center\"><em>Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')}</em></p>\n")
    lines.append("---\n")

    # Coverage Section
    coverage = parse_coverage_html()
    if coverage:
        lines.append("## Test Coverage\n")
        lines.append("| Metric | Coverage | Covered | Total |")
        lines.append("|--------|----------|---------|-------|")
        lines.append(f"| **Function** | **{coverage['function']['percent']:.2f}%** | {coverage['function']['covered']:,} | {coverage['function']['total']:,} |")
        lines.append(f"| **Line** | **{coverage['line']['percent']:.2f}%** | {coverage['line']['covered']:,} | {coverage['line']['total']:,} |")
        lines.append(f"| **Region** | **{coverage['region']['percent']:.2f}%** | {coverage['region']['covered']:,} | {coverage['region']['total']:,} |")
        lines.append(f"| **Branch** | **{coverage['branch']['percent']:.2f}%** | {coverage['branch']['covered']:,} | {coverage['branch']['total']:,} |")
        lines.append("")
    else:
        lines.append("## Test Coverage\n")
        lines.append("> Coverage data not available. Run `./scripts/coverage.sh` to generate.\n")

    # Security Audit Section
    lines.append("## Security Audit\n")
    audit = run_cargo_audit()
    if audit['clean']:
        lines.append(f"**No vulnerabilities found** — scanned {audit['crates_scanned']} crates against {audit['advisories']} advisories\n")
    else:
        lines.append(f"**Vulnerabilities detected** — run `cargo audit` for details\n")

    # Update README.md badges
    update_readme_badges(coverage, audit)

    # Code Stats Section
    lines.append("## Code Statistics\n")

    full_output = run_cmd("tokei crates --sort code")
    full_stats = parse_tokei_rust(full_output)

    prod_output = run_cmd("tokei crates --sort code --exclude '**/tests/**' --exclude '**/benches/**'")
    prod_stats = parse_tokei_rust(prod_output)

    if full_stats and prod_stats:
        test_code = full_stats['code'] - prod_stats['code']
        test_lines = full_stats['lines'] - prod_stats['lines']
        test_files = full_stats['files'] - prod_stats['files']

        lines.append("| Metric | Production | Tests | Total |")
        lines.append("|--------|------------|-------|-------|")
        lines.append(f"| **Code Lines** | {prod_stats['code']:,} | {test_code:,} | {full_stats['code']:,} |")
        lines.append(f"| **Total Lines** | {prod_stats['lines']:,} | {test_lines:,} | {full_stats['lines']:,} |")
        lines.append(f"| **Files** | {prod_stats['files']:,} | {test_files:,} | {full_stats['files']:,} |")
        lines.append(f"| **Comments** | {prod_stats['comments']:,} | - | {full_stats['comments']:,} |")
        lines.append("")

        if prod_stats['code'] > 0:
            ratio = test_code / prod_stats['code']
            lines.append(f"> **Test/Code Ratio:** `{ratio:.2f}x` — {test_code:,} test lines / {prod_stats['code']:,} production lines\n")

    # Test Count Section
    lines.append("## Tests\n")

    total_tests, tests_by_package = count_tests()

    assertions = count_assertions('crates')
    total_assertions = sum(assertions.values())

    lines.append("| Metric | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| **Total Tests** | {total_tests:,} |")
    lines.append(f"| **Total Assertions** | {total_assertions:,} |")
    if total_tests > 0:
        lines.append(f"| **Assertions/Test** | {total_assertions / total_tests:.1f} |")
    if prod_stats and prod_stats['code'] > 0:
        lines.append(f"| **Lines/Test** | {prod_stats['code'] / total_tests:.1f} |")
    lines.append("")

    lines.append("<details>")
    lines.append("<summary>Assertion Breakdown</summary>\n")
    lines.append("| Macro | Count |")
    lines.append("|-------|-------|")
    for macro, count in sorted(assertions.items(), key=lambda x: x[1], reverse=True):
        lines.append(f"| `{macro}` | {count:,} |")
    lines.append("")
    lines.append("</details>\n")

    # Per-crate breakdown
    lines.append("## Per-Crate Breakdown\n")
    lines.append("| Crate | Production Code | Tests |")
    lines.append("|-------|-----------------|-------|")

    crates = find_crates()
    crate_stats = []

    for crate_path, package in crates:
        crate_name = str(crate_path).replace('crates/', '')

        # tokei counts the whole subtree, and a crate that holds other crates
        # in its subdirectories would carry their code in its own row and again
        # in theirs.
        nested = ' '.join(
            f"--exclude '{other.relative_to(crate_path)}'"
            for other, _ in crates
            if other != crate_path and crate_path in other.parents
        )

        prod_out = run_cmd(
            f"tokei --exclude '**/tests/**' --exclude '**/benches/**' {nested}",
            cwd=str(crate_path)
        )
        prod = parse_tokei_rust(prod_out)

        tests = tests_by_package.get(package, 0)

        if prod and prod['code'] > 0:
            crate_stats.append((crate_name, prod['code'], tests))
            lines.append(f"| `{crate_name}` | {prod['code']:,} | {tests} |")

    if crate_stats:
        total_prod = sum(c[1] for c in crate_stats)
        total_crate_tests = sum(c[2] for c in crate_stats)
        lines.append(f"| **Total** | **{total_prod:,}** | **{total_crate_tests}** |")

    lines.append("")

    lines.append("---\n")
    lines.append("<p align=\"center\"><sub>Generated with <code>python scripts/insights.py</code></sub></p>")

    output = '\n'.join(lines)
    Path('INSIGHTS.md').write_text(output)
    print(f"Generated INSIGHTS.md")
    print(f"Updated README.md badges")
    print(f"   Coverage: {coverage['line']['percent']:.2f}% lines" if coverage else "   Coverage: N/A")
    print(f"   Tests: {total_tests}")
    print(f"   Assertions: {total_assertions}")

if __name__ == '__main__':
    main()
