[tasks.build]
args        = ["build", "-p", "wallet-example", "--release"]
command     = "cargo"
description = "Build wallet example in release mode"

[tasks.run]
args        = ["run", "-p", "wallet-example", "--release"]
command     = "cargo"
description = "Run wallet example in release mode"
